// Writes the legal documents out as pages of the website.
//
// The text lives in one place, mobile/src/legal/documents.ts, which the app
// renders on its Legal screen. The site used to have no copy at all - yet the
// age gate keeps /legal readable because it asks people to agree to these, and
// the email to a parent says the terms and the privacy policy are linked from
// the page it opens. This renders the very same data into /legal/*.html, so
// the two cannot say different things.
//
//   node --experimental-strip-types tools/build-legal.mjs
//
// Re-run it after changing documents.ts (Node 22.6 or newer - it imports the
// TypeScript file directly). The navbar is copied from 404.html so a page made
// here matches the rest of the site; tools/sync-nav.mjs keeps it in step after
// that.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { LEGAL_DOCUMENTS, LEGAL_UPDATED } = await import(
  pathToFileURL(join(root, 'mobile/src/legal/documents.ts')).href
);

const escape = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const nav = readFileSync(join(root, '404.html'), 'utf8')
  .replace(/\r\n/g, '\n')
  .match(/<nav class="navbar">[\s\S]*?<\/nav>/)[0];

// Paragraphs, with a run of "- " lines drawn as one list - the same rule the
// app's Legal screen applies.
function bodyHtml(lines) {
  const out = [];
  let list = [];
  const flush = () => {
    if (list.length) out.push(`        <ul>\n${list.map((l) => `          <li>${escape(l)}</li>`).join('\n')}\n        </ul>`);
    list = [];
  };
  for (const line of lines) {
    if (line.startsWith('- ')) {
      list.push(line.slice(2));
    } else {
      flush();
      out.push(`        <p>${escape(line)}</p>`);
    }
  }
  flush();
  return out.join('\n');
}

function page(doc) {
  const url = `https://psekiewicz.github.io/legal/${doc.key}.html`;
  const tabs = LEGAL_DOCUMENTS.map(
    (d) =>
      `<a href="/legal/${d.key}.html"${d.key === doc.key ? ' aria-current="page"' : ''}>${escape(d.title)}</a>`
  ).join('\n        ');
  const sections = doc.sections
    .map((s) => `      <section>\n        <h2>${escape(s.heading)}</h2>\n${bodyHtml(s.body)}\n      </section>`)
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <script>(function(){var t=localStorage.getItem('theme');if(t==='light'||t==='dark')document.documentElement.setAttribute('data-theme',t);})();</script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escape(doc.title)} - Showcase</title>
  <meta name="description" content="${escape(doc.summary)}" />
  <meta property="og:type" content="website" />
  <meta property="og:site_name" content="Showcase" />
  <meta property="og:title" content="${escape(doc.title)} - Showcase" />
  <meta property="og:description" content="${escape(doc.summary)}" />
  <meta property="og:url" content="${url}" />
  <meta property="og:image" content="https://psekiewicz.github.io/icons/social-preview.png" />
  <link rel="canonical" href="${url}" />
  <link rel="stylesheet" href="/css/style.css" />
  <link rel="stylesheet" href="/css/social.css" />
  <link rel="icon" href="/icons/icon-192.png" />
  <link rel="manifest" href="/manifest.webmanifest" />
  <meta name="theme-color" content="#fdf7ea" media="(prefers-color-scheme: light)" />
  <meta name="theme-color" content="#1b1917" media="(prefers-color-scheme: dark)" />
  <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
</head>
<body>
  <!-- Generated by tools/build-legal.mjs from mobile/src/legal/documents.ts - edit that, not this. -->
  ${nav}

  <main>
    <article class="container legal-page">
      <nav class="legal-tabs" aria-label="Legal documents">
        ${tabs}
      </nav>
      <h1>${escape(doc.title)}</h1>
      <p class="legal-summary">${escape(doc.summary)}</p>
      <p class="legal-updated">Last updated ${escape(LEGAL_UPDATED)}</p>
${sections}
    </article>
  </main>

  <script type="module" src="/js/theme.js"></script>
  <script type="module" src="/js/nav.js"></script>
  <script type="module" src="/js/bottom-nav.js"></script>
  <script type="module" src="/js/cookie-consent.js"></script>
  <script type="module" src="/js/pwa.js"></script>
  <script type="module" src="/js/animations.js"></script>
</body>
</html>
`;
}

mkdirSync(join(root, 'legal'), { recursive: true });
for (const doc of LEGAL_DOCUMENTS) {
  writeFileSync(join(root, 'legal', `${doc.key}.html`), page(doc));
}
console.log(`legal pages written: ${LEGAL_DOCUMENTS.map((d) => `legal/${d.key}.html`).join(', ')}`);
